"""
ml.constants
============
Single source of truth for the canonical symptom list.

All training, preprocessing, and inference code must import from here
to guarantee that the feature vectors are consistent across all models.
"""

SYMPTOM_LIST: list[str] = [
    # Respiratory / systemic
    "fever",
    "high_fever",
    "mild_fever",
    "dry_cough",
    "fatigue",
    "headache",
    "sore_throat",
    "body_ache",
    "chest_pain",
    "shortness_of_breath",
    "chills",
    "sweating",
    "runny_nose",
    "sneezing",
    # Gastrointestinal
    "nausea",
    "vomiting",
    "diarrhea",
    "abdominal_pain",
    "stomach_pain",
    "loss_of_appetite",
    "indigestion",
    "acidity",
    "constipation",
    "belly_pain",
    # Neurological / musculoskeletal
    "dizziness",
    "joint_pain",
    "muscle_weakness",
    "blurred_vision",
    "confusion",
    "seizure",
    "stiff_neck",
    "back_pain",
    "neck_pain",
    "weakness_in_limbs",
    "movement_stiffness",
    # Skin / lymphatic
    "rash",
    "itching",
    "skin_rash",
    "pus_filled_pimples",
    "blackheads",
    "scurring",
    "skin_peeling",
    "silver_like_dusting",
    "small_dents_in_nails",
    "inflammatory_nails",
    "blister",
    "red_sore_around_nose",
    "yellow_crust_ooze",
    "dischromic_patches",
    "nodal_skin_eruptions",
    # Urinary
    "burning_micturition",
    "spotting_urination",
    "dark_urine",
    "yellow_urine",
    # Jaundice / liver
    "yellowing_of_eyes",
    "yellowish_skin",
    "loss_of_balance",
    # Metabolic / endocrine
    "weight_loss",
    "weight_gain",
    "excessive_hunger",
    "increased_appetite",
    "polyuria",
    "obesity",
    # Vascular / cardiovascular
    "varicose_veins",
    "swollen_legs",
    "swollen_blood_vessels",
    "prominent_veins_on_calf",
    "cramps",
    # Emergency / severe
    "arm_pain",
    "jaw_pain",
    "facial_drooping",
    "speech_difficulty",
    # Sensory
    "loss_of_taste",
    "loss_of_smell",
    "sensitivity_to_light",
    "sensitivity_to_sound",
    # Other
    "cough",
    "mucoid_sputum",
    "rusty_sputum",
    "phlegm",
    "throat_irritation",
    "redness_of_eyes",
    "sinus_pressure",
    "congestion",
    "breathlessness",
    "family_history",
    "toxic_look_typhos",
    "continuous_sneezing",
    "watering_from_eyes",
    "patches_in_throat",
    "irregular_sugar_level",
    "lethargy",
    "enlarged_thyroid",
    "brittle_nails",
    "swollen_extremeties",
    "excessive_sweating",
    "dehydration",
    "anxiety",
    "cold_hands_and_feets",
    "mood_swings",
    "slurred_speech",
    "palpitations",
    "swelling_joints",
    "painful_walking",
    "puffy_face_and_eyes",
    "sunken_eyes",
    "muscle_pain",
    "altered_sensorium",
    "red_spots_over_body",
    "belly_pain",
    "abnormal_menstruation",
    "bloody_stool",
    "irritation_in_anus",
    "pain_during_bowel_movements",
    "pain_in_anal_region",
    "bruising",
    "swollen_lymph_nodes",
    "malaise",
    "fluid_overload",
    "passage_of_gases",
    "internal_itching",
    "continuous_feel_of_urine",
    "bladder_discomfort",
    "foul_smell_of_urine",
    "receiving_blood_transfusion",
    "history_of_alcohol_consumption",
    "blood_in_sputum",
    "prominent_veins_on_calf",
    "acute_liver_failure",
    "stomach_bleeding",
    "distention_of_abdomen",
    "swelling_of_stomach",
    "hip_joint_pain",
    "knee_pain",
    "swollen_legs",
    "spinning_movements",
    "unsteadiness",
    "visual_disturbances",
]

# De-duplicate while preserving order
_seen: set[str] = set()
SYMPTOM_LIST = [s for s in SYMPTOM_LIST if not (s in _seen or _seen.add(s))]  # type: ignore[func-returns-value]
